import { MigrationInterface, QueryRunner } from 'typeorm';

const taxisList = [
  'GoCatch',
  'Uber',
  'InGoGo',
  'ComfortDelGro',
  'Taxify',
  'taxi.eu',
  'mytaxi',
  'Maxim Taxi',
  'Omega Taxi',
  'Yandex.Taxi',
  'GG Taxi',
  'Uber BY',
  'NextApp',
  'Friday',
  'eCab',
  'TaxiMe',
  'Triumf Taxi',
  'Gett',
  'Kabbee',
  'City Taxi',
  'Főtaxi',
  'GrabTaxi',
  'HKTaxi',
  'Flytaxi',
  'DiDi Hong Kong',
  'God Taxi 85',
  'SynCab',
  'Beat',
  'TAXA 4×35',
  'Careem',
  'Ola Cabs',
  'My Blue Bird',
  'Go-Jek',
  'Lynk',
  'Cabify',
  'it Taxi',
  'InDriver',
  'PassApp',
  'EXNET Taxi',
  'iTsumo',
  'QatarTaxi',
  'Little Cab',
  'Mondo Ride',
  'nTaxi',
  'Namba Taxi',
  'DiDi',
  'EasyTaxi',
  'Easy Tappsi',
  'eTAKSI',
  'iTaxi',
  'Oway Ride',
  'Mivai',
  'Norges Taxi',
  'Dubai Taxi',
  'CAB4YOU',
  'Chauffeur Privé',
  'Star Taxi',
  'Clever Taxi',
  'Cammeo',
  'CAR:GO',
  'HOPIN',
  'Liftago',
  'TaxiMetro',
  'Lyft',
  'Curb',
  'Juno',
  'GoBike',
  'BiTaksi',
  'MyTaxi.uz',
  'Uklon',
  'OnTaxi',
  'Bond Taxi',
  'MiCab',
  'Menevä',
  'Taksi Helsinki',
  'G7',
  'LeCab',
  'EkoTaxi',
  'JapanTaxi',
  'Takkun Tokyo Taxi',
  'Talixo',
  'Taxi 020',
  'Taxi Stockholm',
];

export class AddTaxisListNew1720358553572 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    for (const taxi of taxisList) {
      await queryRunner.query(`INSERT INTO taxi (name) VALUES ($1)`, [taxi]);
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DELETE FROM taxi');
  }
}
