import { MigrationInterface, QueryRunner } from 'typeorm';

const countryRentals = [
  {
    countryName: 'USA',
    rentals: [
      'Airbnb',
      'Vrbo',
      'Booking.com',
      'HomeAway',
      'Zillow',
      'Apartments.com',
      'Rent.com',
      'Sublet.com',
      'Nestpick',
      'Expedia',
      'Hotels.com',
      'Agoda',
      'TripAdvisor',
      'Priceline',
      'Orbitz',
      'Trivago',
      'Kayak',
      'Hotwire',
      'Couchsurfing',
      'Hostelworld',
      'Roomster',
      'Homestay.com',
    ],
  },
  {
    countryName: 'United Kingdom',
    rentals: [
      'Airbnb',
      'Vrbo',
      'Booking.com',
      'HomeAway',
      'Nestpick',
      'Spotahome',
      'Expedia',
      'Hotels.com',
      'Agoda',
      'TripAdvisor',
      'Priceline',
      'Trivago',
      'Kayak',
      'Couchsurfing',
      'Hostelworld',
      'Roomster',
      'Homestay.com',
    ],
  },
  {
    countryName: 'Germany',
    rentals: [
      'Airbnb',
      'Vrbo',
      'Booking.com',
      'HomeAway',
      'Nestpick',
      'Spotahome',
      'Expedia',
      'Hotels.com',
      'Agoda',
      'TripAdvisor',
      'Priceline',
      'Trivago',
      'Kayak',
      'Couchsurfing',
      'Hostelworld',
      'Roomster',
      'Homestay.com',
    ],
  },
  {
    countryName: 'France',
    rentals: [
      'Airbnb',
      'Vrbo',
      'Booking.com',
      'HomeAway',
      'Nestpick',
      'Spotahome',
      'Expedia',
      'Hotels.com',
      'Agoda',
      'TripAdvisor',
      'Priceline',
      'Trivago',
      'Kayak',
      'Couchsurfing',
      'Hostelworld',
      'Roomster',
      'Homestay.com',
    ],
  },
  {
    countryName: 'Spain',
    rentals: [
      'Airbnb',
      'Vrbo',
      'Booking.com',
      'HomeAway',
      'Nestpick',
      'Spotahome',
      'Expedia',
      'Hotels.com',
      'Agoda',
      'TripAdvisor',
      'Priceline',
      'Trivago',
      'Kayak',
      'Couchsurfing',
      'Hostelworld',
      'Roomster',
      'Homestay.com',
    ],
  },
  {
    countryName: 'Italy',
    rentals: [
      'Airbnb',
      'Vrbo',
      'Booking.com',
      'HomeAway',
      'Nestpick',
      'Spotahome',
      'Expedia',
      'Hotels.com',
      'Agoda',
      'TripAdvisor',
      'Priceline',
      'Trivago',
      'Kayak',
      'Couchsurfing',
      'Hostelworld',
      'Roomster',
      'Homestay.com',
    ],
  },
  {
    countryName: 'China',
    rentals: [
      'Airbnb',
      'Booking.com',
      'HomeAway',
      'Nestpick',
      'Expedia',
      'Hotels.com',
      'Agoda',
      'TripAdvisor',
      'Trivago',
      'Kayak',
      'Couchsurfing',
      'Hostelworld',
      'Roomster',
      'Homestay.com',
    ],
  },
  {
    countryName: 'Japan',
    rentals: [
      'Airbnb',
      'Booking.com',
      'HomeAway',
      'Nestpick',
      'Expedia',
      'Hotels.com',
      'Agoda',
      'TripAdvisor',
      'Trivago',
      'Kayak',
      'Couchsurfing',
      'Hostelworld',
      'Roomster',
      'Homestay.com',
    ],
  },
  {
    countryName: 'India',
    rentals: [
      'Airbnb',
      'Booking.com',
      'HomeAway',
      'Nestpick',
      'Expedia',
      'Hotels.com',
      'Agoda',
      'TripAdvisor',
      'Trivago',
      'Kayak',
      'Couchsurfing',
      'Hostelworld',
      'Roomster',
      'Homestay.com',
    ],
  },
  {
    countryName: 'Thailand',
    rentals: [
      'Airbnb',
      'Vrbo',
      'Booking.com',
      'HomeAway',
      'Nestpick',
      'Expedia',
      'Hotels.com',
      'Agoda',
      'TripAdvisor',
      'Priceline',
      'Trivago',
      'Kayak',
      'Couchsurfing',
      'Hostelworld',
      'Roomster',
      'Homestay.com',
    ],
  },
  {
    countryName: 'Egypt',
    rentals: [
      'Airbnb',
      'Vrbo',
      'Booking.com',
      'HomeAway',
      'Nestpick',
      'Expedia',
      'Hotels.com',
      'Agoda',
      'TripAdvisor',
      'Priceline',
      'Trivago',
      'Kayak',
      'Couchsurfing',
      'Hostelworld',
      'Roomster',
      'Homestay.com',
    ],
  },
  {
    countryName: 'Kenya',
    rentals: [
      'Airbnb',
      'Vrbo',
      'Booking.com',
      'HomeAway',
      'Nestpick',
      'Expedia',
      'Hotels.com',
      'Agoda',
      'TripAdvisor',
      'Priceline',
      'Trivago',
      'Kayak',
      'Couchsurfing',
      'Hostelworld',
      'Roomster',
      'Homestay.com',
    ],
  },
  {
    countryName: 'Australia',
    rentals: [
      'Airbnb',
      'Vrbo',
      'Booking.com',
      'HomeAway',
      'Nestpick',
      'Expedia',
      'Hotels.com',
      'Agoda',
      'TripAdvisor',
      'Priceline',
      'Trivago',
      'Kayak',
      'Couchsurfing',
      'Hostelworld',
      'Roomster',
      'Homestay.com',
    ],
  },
  {
    countryName: 'UAE',
    rentals: [
      'Airbnb',
      'Vrbo',
      'Booking.com',
      'HomeAway',
      'Nestpick',
      'Expedia',
      'Hotels.com',
      'Agoda',
      'TripAdvisor',
      'Priceline',
      'Trivago',
      'Kayak',
      'Couchsurfing',
      'Hostelworld',
      'Roomster',
      'Homestay.com',
    ],
  },
  {
    countryName: 'Israel',
    rentals: [
      'Airbnb',
      'Vrbo',
      'Booking.com',
      'HomeAway',
      'Nestpick',
      'Expedia',
      'Hotels.com',
      'Agoda',
      'TripAdvisor',
      'Priceline',
      'Trivago',
      'Kayak',
      'Couchsurfing',
      'Hostelworld',
      'Roomster',
      'Homestay.com',
    ],
  },
];

const getRentals = (rentals: string[]) =>
  rentals.map((rental) => `'${rental}'`).join(',');

export class AddCountryRentalsList1720358849846 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    for (const { countryName, rentals } of countryRentals) {
      const [country] = await queryRunner.query(
        'SELECT id FROM country WHERE name = $1',
        [countryName],
      );

      if (country) {
        const foundRentals = await queryRunner.query(
          `SELECT id FROM rental WHERE name IN (${getRentals(rentals)})`,
        );

        if (foundRentals?.length) {
          for (const foundRental of foundRentals) {
            await queryRunner.query(
              `INSERT INTO country_rental (country_id, rental_id) VALUES ($1, $2)`,
              [country.id, foundRental.id],
            );
          }
        }
      }
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DELETE FROM country_rental');
  }
}
